<?php

use Model\Translate;

$listLang = Translate::getTranslateDefault();
?>
<ol class="breadcrumb">
    <li><a href="/backend">Dashboard</a></li>
    <li>Dịch </li>
</ol>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Dịch</h3>
        </div>
        <div class="box-body">
            <div class="table-responsive">
                <div role="tabpanel">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="/options/translate/vi/">Tiếng Việt</a>
                        </li>
                        <li>
                            <a href="/options/translate/en/">Tiếng Anh</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <?php
                        include("Form.phtml");
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>