<?php
$modelAdv = new Model\adv();
$advs = $modelAdv->AdvsByGroup("homeslide", FALSE);


//$advs = $adv->AdvsByGroup("homeslide", false);


$carouselitem[] = "carousel-item-eight";
$carouselitem[] = "carousel-item-nine";
$carouselitem[] = "carousel-item-ten";
?>
<div class="page-slider margin-bottom-40">
    <div id="carousel-example-generic" class="carousel slide carousel-slider">
        <ol class="carousel-indicators carousel-indicators-frontend">
            <?php
            foreach ($advs as $key => $value) {
                ?>
                <li data-target="#carousel-example-generic" data-slide-to="<?php echo $key; ?>" class="<?php echo $key == 0 ? 'active' : '' ?>"></li>
                <?php
            }
            ?>
        </ol>
        <div class="carousel-inner" role="listbox">
            <?php
            $dem = 0;
            foreach ($advs as $key => $value) {
                $dem = $dem % 3;
                $advs = new Model\adv($value);
                $carouselitem[$key];
                ?>
                <div class="item  <?php
                echo $carouselitem[$dem] . " ";
                echo $key == 0 ? 'active' : ''
                ?> " style="background-image: url('<?php echo $advs->Urlimages; ?>')" >
                    <div class="container">
                        <div class="carousel-position-six text-uppercase text-center">
                            <h2 class="margin-bottom-20 animate-delay carousel-title-v5" data-animation="animated fadeInDown">
                                <?php echo $advs->Content; ?><br/>
                            </h2>
                        </div>
                    </div>
                </div>
                <?php
                $dem++;
            }
            ?>

        </div>
        <a class="left carousel-control carousel-control-shop carousel-control-frontend" target="_self" href="#carousel-example-generic" role="button" >
            <i class="fa fa-angle-left" aria-hidden="true"></i>
        </a>
        <a class="right carousel-control carousel-control-shop carousel-control-frontend" target="_self" href="#carousel-example-generic" role="button" >
            <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="main">
    <div class="container">
        <!-- BEGIN SERVICE BOX -->
        <div class="row quote-v1 margin-bottom-30">
            <div class="col-md-9">
                <span>Product</span>
            </div>
            <div class="col-md-3 text-right">
            </div>
        </div>

        <div class="row recent-work margin-bottom-40">
            <div class="" >
                <div class=" ">
                    <div style="" >
                        <!--                        <div ng-repeat="item in _DanhMucSanPham" class=" col-md-4">
                                                    <div class="recent-work-item" >
                                                        <em>
                                                            <img style="margin: auto;height: 228px;"
                                                                 on-error-src="/public/no-image.jpg"
                                                                 src="{{item.Image}}" alt="{{item.Name}}" class="img-responsive">
                                                            <a href="{{item.Link}}"><i class="fa fa-link"></i></a>
                                                            <a href="{{item.Link}}" class="fancybox-button" title="{{item.Name}}" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                                        </em>
                                                        <a class="recent-work-description" href="{{item.Link}}">
                                                            <strong class="text-uppercase" >{{item.Name}}</strong>
                                                        </a>
                                                    </div>
                                                </div>-->
                        <div ng-repeat="item in _AdvProducts" class=" col-md-4">
                            <div class="recent-work-item" >
                                <em>
                                    <img style="margin: auto;height: 228px;"
                                         on-error-src="/public/no-image.jpg"
                                         src="{{item.Urlimages}}" alt="{{item.Name}}" class="img-responsive">
                                    <a target="_blank" href="{{item.Link}}"><i class="fa fa-link"></i></a>
                                    <a target="_blank" href="{{item.Link}}" class="fancybox-button" title="{{item.Name}}" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="{{item.Link}}">
                                    <strong class="text-uppercase" >{{item.Name}}</strong>
                                </a>
                            </div>
                        </div>

                        <div class="clearfix" ></div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row margin-bottom-40 front-steps-wrapper front-steps-count-3">
            <div class="col-md-3 col-sm-3 front-step-col">
                <div class="front-step front-step1">
                    <h2 style="font-size: 1.3em;height: 1.3em" >Material and machinery equipment</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 front-step-col">
                <div class="front-step front-step1">
                    <h2  style="font-size: 1.3em;height: 1.3em">Technical consultancy</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 front-step-col">
                <div class="front-step front-step1">
                    <h2 style="font-size: 1.3em;height: 1.3em">System design</h2>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 front-step-col">
                <div class="front-step front-step4">
                    <h2 style="font-size: 1.3em;height: 1.3em">Operation and experiment of industrial equipment</h2>
                </div>
            </div>
        </div>
        <!-- END STEPS -->                <!-- BEGIN CLIENTS -->


        <!-- END CLIENTS -->
    </div>
</div>