<?php
$view_theme = new \theme\qmts\functionLayout();
$_Pages = new \Model\pages($data["pages"]);
$Model_News = new \Model\news();
$newsByPage = $Model_News->NewsByPagesLimitNumber($_Pages->idPa, 9, FALSE);
?>

<div class="container" >
    <div  >
        <h2  style="padding: 10px;font-weight: bold;font-size: 20px;margin-bottom: 20px;" >
            <span style="padding: 10px;border-bottom: 1px solid #0088CC;" >
                <?php echo $_Pages->Name ?>
            </span>
        </h2>
        <?php
        if ($newsByPage)
            foreach ($newsByPage as $_news) {
                $news = new \Model\news($_news);
                ?>
                <div class="col-md-3 item" style="margin-bottom: 30px;"  >
                    <div class="post" >
                        <div class="post-thumb image-hover2 " style="margin: auto;" >
                            <a href="<?php echo $news->linkNewsCurent(); ?>">
                                <img  style="height: 200px;" onerror="this.src='/public/home/assets/data/option3/blog1.jpg'" class="img img-responsive" src="<?php echo $_news["UrlHinh"] ?>" alt="<?php echo $_news["Name"] ?>">
                            </a>
                        </div>
                        <div class="post-desc">
                            <h3 class="post-title text-center">
                                <a  href="<?php echo $news->linkNewsCurent(); ?>" style="padding: 10px;height: 50px;overflow: hidden;display: block" ><?php echo $_news["Name"] ?></a>
                            </h3>
                        </div>
                    </div>
                </div>
                <?php
            }
        ?>
    </div>
</div>

