<?php
$functionLayout = new theme\luatkimsa\functionLayout();
echo " ";
flush();
?>
<!DOCTYPE html>
<html lang="vi" ng-cloak="TRUE" ng-app="rootApp"   ng-controller="homeController" >
    <head>
        <?php
        $functionLayout->gethtml();
        flush();
        ?>
    </head>
    <body class="corporate">

        <?php
        $functionLayout->header();
        $functionLayout->Menu();
        ?>
        <div class="container" >
            <div class="row" >
                <?php
                include $Content;
                ?>

            </div>
        </div>
        <?php
        $functionLayout->footer();
        $functionLayout->js();
        ?>
    </body>


</html>
<?php
$functionLayout->DeCodeHTML();
flush();
?>