
<div class="main">
    <div class="container">
        <div class="row margin-bottom-40">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12">
                <div class="content-page">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="map" class="gmaps margin-bottom-40" style="height:400px;"></div>
                        </div>
                        <div class=" col-sm-8">
                            <h1 class="text-left title-pannel" ><span>Liên Hệ</span></h1>
                            <p>
                                Gửi Thông Tin Cho Chúng Tôi
                            </p>

                            <!-- BEGIN FORM-->
                            <form action="#" role="form">
                                <div class="form-group">
                                    <label for="contacts-name">Họ & Tên</label>
                                    <input type="text" class="form-control" id="contacts-name">
                                </div>
                                <div class="form-group">
                                    <label for="contacts-email">Email</label>
                                    <input type="email" class="form-control" id="contacts-email">
                                </div>
                                <div class="form-group">
                                    <label for="contacts-message">Nội Dung</label>
                                    <textarea class="form-control" rows="5" id="contacts-message"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Gửi </button>
                                <button type="reset" class="btn btn-default"> Làm Lại</button>
                            </form>
                            <!-- END FORM-->
                        </div>

                        <div class="col-sm-4 sidebar2">
                            <h1 class="text-left title-pannel" ><span>Thông Tin Công Ty</span></h1>
                            <address class="margin-bottom-40">
                                <p>Địa Chỉ: __DiaChi___</p>
                                <p>Phone: __SDT___</p>
                                <p>Fax: __Fax___</p>
                                <p>Email: <a href="mailto:__Email___">__Email___</a></p>
                                <p>Skype: <a href="skype:__Skyper___">__Skyper___</a></p>
                            </address>
                            <ul class="social-icons margin-bottom-40">
                                <li><a href="javascript:;" data-original-title="facebook" class="facebook"></a></li>
                                <li><a href="javascript:;" data-original-title="github" class="github"></a></li>
                                <li><a href="javascript:;" data-original-title="Goole Plus" class="googleplus"></a></li>
                                <li><a href="javascript:;" data-original-title="linkedin" class="linkedin"></a></li>
                                <li><a href="javascript:;" data-original-title="rss" class="rss"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
    </div>
</div>


<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
<script src="/public/bdsltp/public/theme/assets/plugins/gmaps/gmaps.js" type="text/javascript"></script>
<script src="/public/bdsltp/public/theme/assets/pages/scripts/contact-us.js" type="text/javascript"></script>