<?php
if (!isset($functionLayout))
    $functionLayout = new \theme\noithathoaphatgiagoc\functionLayout();

//print_r($data);
$Name = $data["keyword"];
$Id = $data["danhmuc"];
$product = new Model\Products();
$ModelCat = new Model\Category();
$Cats = [$Id];
$ModelCat->AllCategoryByParentID([$Id], $Cats);
//$Produc->ProductsByCatID($Cats, $page, $number, $sum);
//var_dump($Cats);
$sum = 0;
$page = 1;
$number = 24;
$DSProduct = $product->ProductsByCatIDAndName($Cats, $Name, $page, $number, $sum);
?>
<div style="margin-top: 0px;" id="view-product-list" class="view-product-list">
    <h2 class="page-heading">
        <span class="page-heading-title">Tìm Kiếm</span>
    </h2>
    <ul class="display-product-option">
        <li class="view-as-grid selected">
            <span>grid</span>
        </li>
        <li class="view-as-list">
            <span>list</span>
        </li>
    </ul>
    <!-- PRODUCT LIST -->
    <ul class="row product-list grid">
        <?php
        if ($DSProduct)
            foreach ($DSProduct as $_Poroduct) {
                ?>
                <li class="col-xs-6 col-sm-3">
                    <?php
                    $functionLayout->product($_Poroduct);
                    ?>
                </li>
                <?php
            }
        ?>

    </ul>
    <!-- ./PRODUCT LIST -->
</div>
