<?php
$Model_Duser = new Module\duser\Model\Duser();
$DSOption = $Model_Duser->Admins(FALSE);
?>
<div class="clearfix" ></div>
<div class="panel ">
    <div class="panel-heading">
        <!--        <div class="btn btn-group btn-group-sm pull-right" >
                    <a href="__AddLink___" class="btn btn-primary" >__langAdd___ <i class="fa fa-plus" ></i></a>
                </div>-->
        <h3 class="panel-title">Thông Tin Tài Khoản
            <a href="<?php echo \Module\duser\Model\LinkCommon::LinkAddUser() ?>" class="btn btn-default" >
                __langAdd___ <i class="fa fa-plus" ></i>
            </a>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-hover table-compare table-striped" >
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Sđt</th>
                    <th>Địa Chỉ</th>
                    <th>Ghi Chú</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($DSOption as $User) {
                    ?>
                    <tr>
                        <td><?php echo $User["Username"] ?></td>
                        <td><?php echo $User["Email"] ?></td>
                        <td><?php echo $User["Phone"] ?></td>
                        <td><?php echo $User["Address"] ?></td>
                        <td><?php echo $User["Note"] ?></td>
                        <td>
                            <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>" class="btn-sm btn btn-danger xoa" >Xem</a>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Sđt</th>
                    <th>Địa Chỉ</th>
                    <th>Ghi Chú</th>
                    <th>Action</th>
                </tr>
            </tfoot>

        </table>
    </div>
</div>