<?php
$Model_Duser = new Module\duser\Model\Duser();
$name = "";
$index = 1;
$number = 10;
$tong = 0;
$DSOption = $Model_Duser->AdminsPT($name, $index, $number, $tong);
$DSOption = $Model_Duser->Admins(FALSE);
?>
<div class="clearfix" ></div>
<div class="container-fluid">

    <div class="box ">
        <div class="box-header">
            <h3 class="box-title">Thông Tin Tài Khoản</h3>
            <div class="box-tools">
                <a href="<?php echo \Module\duser\Model\LinkCommon::LinkAddUser() ?>" class="btn btn-default" >
                    __langAdd___ <i class="fa fa-plus" ></i>
                </a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-bordered table-hover table-compare table-striped" >
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>SĐT</th>
                        <th>Địa Chỉ</th>
                        <th>Ghi Chú</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($DSOption as $User) {
                        ?>
                        <tr>
                            <td><?php echo $User["Username"] ?></td>
                            <td><?php echo $User["Email"] ?></td>
                            <td><?php echo $User["Phone"] ?></td>
                            <td><?php echo $User["Address"] ?></td>
                            <td><?php echo $User["Note"] ?></td>
                            <td>
                                <a href="<?php echo Module\duser\Model\LinkCommon::LinkEdit($User["Username"]); ?>" class="btn-sm btn btn-danger xoa" >Xem</a>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>SĐT</th>
                        <th>Địa Chỉ</th>
                        <th>Ghi Chú</th>
                        <th>Action</th>
                    </tr>
                </tfoot>

            </table>
        </div>
    </div>
</div>