<?php
$Model_Duser = new Module\duser\Model\Duser();
$DSOption = $Model_Duser->Admins(FALSE);
$User = new \Module\DB\Model\Duser($User);
?>

<div class="col-md-6" >
    <?php
    $Error = Model\Error::getAllError();
    if ($Error) {
        ?>
        <div class="col-sm-12" >
            <div style="position: fixed;top: 100px;right: 0px;width: 300px;z-index: 1999"  class="alert alert-<?php echo $Error["Type"] ?> alert-dismissible" >
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <?php echo $Error["Content"]; ?>
            </div>

        </div>
        <?php
    }
    ?>
    <form method="post" action="" enctype="multipart/form-data" >
        <div class="panel panel-primary">
            <div class="panel-heading ">
                <h3 class="panel-title" >Sửa Tài Khoản</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="">Họ & Tên</label>
                    <input type="text" value="<?php echo $User->Name; ?>" class="form-control" name="user[Name]"  placeholder="Họ & Tên">
                </div>
                <div class="form-group">
                    <label for="">Tài Khoản</label>
                    <input type="text" readonly="readonly" value="<?php echo $User->Username; ?>" class="form-control" name="user[Username]"  placeholder="Tài Khoản">
                </div>

                <div class="form-group">
                    <label for="">Email</label>
                    <input type="email" value="<?php echo $User->Email; ?>" class="form-control" name="user[Email]"  placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="">SĐT</label>
                    <input type="text" value="<?php echo $User->Phone; ?>" class="form-control" name="user[Phone]"  placeholder="SĐT">
                </div>
                <div class="form-group  ">
                    <label for="">Nhóm</label>
                    <select   class="form-control" name="user[Groups]"  >
                        <option <?php echo $User->Groups == 0 ? 'selected="selected"' : ''; ?>  value="0" >Admin</option>
                        <option <?php echo $User->Groups == 1 ? 'selected="selected"' : ''; ?>  value="1" >Chỉnh Sửa Nội Dung</option>
                    </select>

                </div>
                <div class="form-group">
                    <label for="">Địa Chỉ</label>
                    <textarea class="form-control" name="user[Address]"  ><?php echo $User->Address; ?></textarea>
                </div>
                <div class="form-group">
                    <label for="">Chi Chú</label>
                    <textarea class="form-control" name="user[Note]"  ><?php echo $User->Note; ?></textarea>
                </div>
                <div class="form-group">
                    <label for=""></label>
                    <input type="submit" class="btn btn-success" name="SaveAdmin"  value="Lưu Thông Tin" >
                </div>
            </div>
        </div>
    </form>
</div>

<div class="col-md-6" >
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Tạo Lại Mật Khẩu</h3>
        </div>
        <div class="panel-body">
            <form action="" method="POST" class="form-horizontal">
                <div class="form-group">
                    <label for="inputName" class="col-sm-4 control-label">Nhập Mật Khẩu</label>
                    <div class="col-sm-6">
                        <input type="hidden" readonly="readonly" value="<?php echo $User->Username; ?>"  name="Username"   >
                        <input type="password" name="Password" id="password" class="form-control"  placeholder="Mật khẩu">
                        <button type="button" data-target="#password" class="XemMatKhau btn btn-success"><i class="fa fa-eye" ></i></button>
                        <button type="button" id="TaoMatKhau" data-target="#password" class="btn btn-success"><i class="fa fa-refresh" ></i></button>
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-6">
                    <button type="submit" name="ResetPassword" class="btn btn-success">Cập Nhật</button>
                </div>
            </form>
        </div>

    </div>
</div>

</div>
