<?php
$adv = new \Model\adv();
$_homeslide = $adv->AdvsByGroup("homeslide", FALSE);
$_homeslideClass = ["carousel-item-eight", "carousel-item-nine", "carousel-item-ten"];
$HomeCategory = \theme\ThemeConfig::getThemConfigByKey(\theme\ThemeConfig::DichVu);
?>
<script type="application/ld+json">
    {
        "@context": "https://schema.org/",
        "@type": "CreativeWorkSeries",
        "name": "<?php echo Model_Seo::$Title ?>",
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "5",
            "bestRating": "5",
            "ratingCount": "1000"
        }
    }
</script>
<div class="main">
    <div class=" margin-bottom-40 fullscreem slider_home " style="">
        <div class="container">
            <div class="row pt-25">
                <div class="col-md-4">
                    <div class="slider_home_item"> 
                        <div class="item-content">
                            <em>
                               
                                <a class="" href="">
                                    <img src="/public/banner/banner1.png" data-wow-duration="1s" alt="Thi Công" class="wow slideInRight img-responsive">
                                </a>
                            </em>
                            <a class="title-baiviet" href="#">
                                <h3 class="wow slideInLeft" data-wow-duration="2s">Thi Công</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="slider_home_item">
                        <div class="item-content">
                            <em>
                                <a class="" href="">
                                    <img src="/public/banner/banner2.png" data-wow-duration="1s" alt="In Ấn" class="wow slideInRight img-responsive">
                                </a>
                            </em>
                            <a class="title-baiviet" href="#">
                                <h3 class="wow slideInLeft" data-wow-duration="2s">In Ấn</h3>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <!-- <div class="octagon"></div> -->
                    <div class="slider_home_item">
                        <div class="item-content text-center">
                            <em>
                                <a class="" href="">
                                    <img src="/public/banner/banner3.png" data-wow-duration="1s" alt="Tổ chức sự kiện" class="wow slideInRight img-responsive">
                                </a>
                            </em>
                            <a class="title-baiviet" href="#">
                                <h3 class="wow slideInLeft" data-wow-duration="2s">Tổ Chức <br> Sự Kiện</h3>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class=" margin-bottom-40 ">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <?php
                    $HomeCategoryID = array_map(function ($item) {
                        return $item["idPa"];
                    }, $HomeCategory);
                    echo theme\dainamhomes\functionLayout::DanhSachDangMuc1($HomeCategoryID);
                    // echo theme\dainamhomes\functionLayout::MauBietThuDep();
                    // echo theme\dainamhomes\functionLayout::TuVanHotLine();
                    // echo theme\dainamhomes\functionLayout::DoiTac();
                    // echo theme\dainamhomes\functionLayout::TinTuc();
                    ?>
                </div>
                <div class="col-md-4">
                    <?php
                    include "right.phtml";
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>