<?php
$_News = new Model\news($data["news"]);
$data["news"]["SoLanXem"] = $data["news"]["SoLanXem"] + 1;
$_News->editNews($data["news"]);
?>
<script type="application/ld+json">
    {
    "@context": "https://schema.org/",
    "@type": "CreativeWorkSeries",
    "name": "<?php echo Model_Seo::$Title ?>",
    "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "5",
    "bestRating": "5",
    "ratingCount": "100"
    }
    }

</script>

<div class="container">
    <ul class="breadcrumb">
        <li><a href="/">Trang Chủ</a></li>
        <li><a href="<?php echo $_News->PageID()->linkPagesCurent(); ?>"><?php echo $_News->PageID()->Name; ?></a></li>
        <li class="active"><?php echo $_News->Name ?></li>
    </ul>
    <?php
    if (isset($_SESSION[QuanTri])) {
        ?>
        <a href="/mnews/editnews/<?php echo $_News->ID; ?>" class="btn btn-primary pull-right" >Sửa</a>
        <?php
    }
    ?>
</div>
<div class="Main-Content" >
    <div class="container" >
        <div class="row">
            <div class="col-md-8">

                <h1 class="text-left text-uppercase text-bold" style="font-size: 24px;" ><?php echo $_News->Name ?></h1>
                <p>
                    <i class="fa fa-calendar" ></i> <?php echo $_News->NgayDang() ?>
                    <i class="fa fa-eye" ></i> <?php echo $_News->SoLanXem ?>
                </p>
                <hr>
                <?php echo $_News->Content; ?>
                <hr>
                Tags:
                <?php
                $tagsDetail = new Model\tags\tagsDetail();
                $tagsDetailBynews = $tagsDetail->GetByNewsId($_News->ID);
                if ($tagsDetailBynews) {
                    foreach ($tagsDetailBynews as $tagsBynews) {
                        $_tagDetai = new Model\tags\tagsDetail($tagsBynews);
                        ?>
                        <a href="<?php echo $_tagDetai->Tags()->LinkTags(); ?>" >
                            <label class="btn btn-default" >
                                <?php echo $_tagDetai->Name; ?>
                            </label>
                        </a>
                        <?php
                    }
                }
                ?>
                <hr>
                Chia Sẻ: <div class="sharethis-inline-share-buttons"></div>
            </div>
            <div class="col-md-4">
                <?php
                include 'right.phtml';
                ?>
            </div>
        </div>

    </div>
</div>
<hr>
<div class="container">
    <h2 class="text-left title-pannel " ><span>Bài Viết Liên Quan </span></h2>
    <ul class="dsbaivietlienquan" >
        <?php
        $newsLienQuan = $_News->BaiVietLienQuan();
        if ($newsLienQuan)
            foreach ($newsLienQuan as $key => $value) {
                $_news = new \Model\news($value);
                ?>
                <li><a href = "<?php echo $_news->linkNewsCurent(); ?>" > <?php echo $_news->Name; ?></a></li>
                <?php
            }
        ?>
    </ul>
</div>