<?php
$_Pages = new \Model\pages($data["pages"]);
$DanhMucBaiViet = $_Pages->PagesByGroup(1, FALSE);
$Model_News = new \Model\news();
$DanhSachTinMoiNhat = $Model_News->DanhSachTinMoiNhat(6);
$newsByPage = $Model_News->NewsByPagesLimitNumber($_Pages->idPa, 9, FALSE);
?>
<div class="container" >
    <div class="" >
        <ul class="breadcrumb">
            <li><a href="/">Trang Chủ</a></li>
            <li class="active"><?php echo $_Pages->Name ?></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-8" >
            <h2 class="text-left title-pannel"><span><?php echo $_Pages->Name ?></span></h2>
            <?php
            if ($newsByPage) {
                foreach ($newsByPage as $news) {
                    $_new = new \Model\news($news);
                    ?>
                    <div class="row" >
                        <div class="col-md-4" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>"  >
                                <img style="height: 200px;" onerror="this.src='/public/lawkimsa/Images/h1.jpg'" class="img img-responsive" src="<?php echo $_new->UrlHinh ?>" alt="<?php echo $_new->Name ?>"/>
                            </a>
                        </div>
                        <div class="col-md-8" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>" class="" >
                                <h3 class="newstitle text-justify" ><?php echo $_new->Name ?></h3>
                            </a>
                            <p><span><?php echo $_new->NgayDang() ?></span>  </p>
                            <p><?php echo $_new->Summary(); ?></p>
                        </div>
                        <div class="clearfix" ></div>
                        <hr>
                    </div>

                    <?php
                }
            }
            ?>
        </div>
        <div class="col-md-4" >
            <h2 class="text-left title-pannel"><span>Danh Mục Bài Viết</span></h2>
            <ul class="list-group margin-bottom-25 sidebar-menu">
                <?php
                if ($DanhMucBaiViet) {
                    foreach ($DanhMucBaiViet as $page) {
                        $_page = new Model\pages($page);
                        ?>
                        <li class="list-group-item clearfix"><a href="<?php echo $_page->linkPagesCurent() ?>"><i class="fa fa-angle-right"></i> <?php echo $_page->Name ?></a></li>
                        <?php
                    }
                }
                ?>
            </ul>
            <h2 class="text-left title-pannel"><span>Tin Mới Nhất</span></h2>
            <?php
            if ($DanhSachTinMoiNhat) {
                foreach ($DanhSachTinMoiNhat as $news) {
                    $_new = new \Model\news($news);
                    ?>
                    <div class="row" >
                        <div class="col-md-3" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>"  >
                                <img style="" onerror="this.src='/public/lawkimsa/Images/h1.jpg'" class="img img-responsive" src="<?php echo $_new->UrlHinh ?>" alt="<?php echo $_new->Name ?>"/>
                            </a>
                        </div>
                        <div class="col-md-9" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>" class="" >
                                <h3 style="font-size: 14px;" class="text-bold text-justify" ><?php echo $_new->Name ?></h3>
                            </a>
                            <p><span><?php echo $_new->NgayDang() ?></span></p>
                        </div>
                        <div class="clearfix" ></div>
                        <hr>
                    </div>

                    <?php
                }
            }
            ?>
        </div>
    </div>
</div>

