<?php
$_Pages = new \Model\pages($data["pages"]);
$indexPage = !empty($data["indexPage"]) ? intval($data["indexPage"]) : 1;
$number = 12;
$DanhMucBaiViet = $_Pages->PagesByType(1, FALSE);
$Model_News = new \Model\news();
$DanhSachTinMoiNhat = $Model_News->DanhSachTinMoiNhat(6);
$tong = 0;
$newsByPage = $Model_News->NewsByPagesLimitNumberPt($_Pages->idPa, $indexPage, $number, $tong);
?>
<div class="container" >
    <div class="" >
        <ul class="breadcrumb">
            <li><a href="/">Trang Chủ</a></li>
            <li class="active"><?php echo $_Pages->Name ?></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-8" >
            <h1 class="text-left title-pannel"><span><?php echo $_Pages->Name ?></span></h1>
            <?php
            if ($newsByPage) {
                foreach ($newsByPage as $news) {
                    $_new = new \Model\news($news);
                    ?>
                    <div class="row" >
                        <div class="col-md-4" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>"  >
                                <img style="height: 200px;" onerror="this.src='/public/lawkimsa/Images/h1.jpg'" class="img img-responsive" src="<?php echo $_new->UrlHinh ?>" alt="<?php echo $_new->Name ?>"/>
                            </a>
                        </div>
                        <div class="col-md-8" >
                            <a href="<?php echo $_new->linkNewsCurent(); ?>" class="" >
                                <h3 class="newstitle text-justify" ><?php echo $_new->Name ?></h3>
                            </a>
                            <p><span><?php echo $_new->NgayDang() ?></span>  </p>
                            <p><?php echo $_new->Summary(); ?></p>
                        </div>
                        <div class="clearfix" ></div>
                        <hr>
                    </div>

                    <?php
                }
            }
            $tongTrang = ceil($tong / $number);
            echo \lib\Common::PhanTrang($tongTrang, $indexPage, "[i]");
            ?>

        </div>
        <div class="col-md-4" >
            <?php
            include "right.phtml";
            ?>
        </div>
    </div>
</div>

