<?php
$a = new Model_Adapter();
$news = $data["news"];
$_new = new \Model\news($news);
$HoiDaps = $_new->HoiDaps();
?>
<script type="text/javascript" >
    app.controller("hoidapController", function($http, $scope) {
        $scope.hoiDap = {
            "Id": null,
            "CauHoi": null,
            "TraLoi": null
        }
        $scope.themCauHoi = function() {
            $scope.hoiDap = {
                "Id": null,
                "CauHoi": null,
                "TraLoi": null
            }
        }
        $scope.chonCauHoi = function(Id, cauHoi, traLoi) {
            $scope.hoiDap = {
                "Id": Id,
                "CauHoi": cauHoi,
                "TraLoi": traLoi
            };
        }
    });
</script>

<div class="row " ng-controller="hoidapController"  >
    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header  ">
                <h3 class="box-title">Thêm Hỏi Đáp</h3>
            </div><!-- /.box-header -->
            <div class="box-body no-padding ">
                <div class="">
                    <div class="col-md-4">
                        <form action="" method="POST" enctype="multipart/form-data" >
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Câu Hỏi: {{CauHoi}}</h3>
                                    <div class="box-tools" >
                                        <button ng-click="themCauHoi()" ng-show="hoiDap.Id != null" type="button" class="btn btn-success" ><i class="fa fa-plus" ></i></button>
                                    </div>
                                </div>
                                <div class="box-body">
                                    <div class="form-group" ng-show="hoiDap.Id" >
                                        <label for="">Mã Câu Hỏi</label>
                                        <input readonly=""  type="text" name="Id" class="form-control" ng-model="hoiDap.Id" >
                                    </div>

                                    <div class="form-group">
                                        <label for="">Câu Hỏi</label>
                                        <input required="required" type="text" name="CauHoi" class="form-control" ng-model="hoiDap.CauHoi" >
                                        <input value="<?php echo $_new->ID; ?>" type="hidden" name="IdBaiViet" class="form-control" >
                                    </div>
                                    <div class="form-group">
                                        <label for="">Trả Lời</label>
                                        <textarea required="required" rows="5" name="TraLoi" type="text" class="form-control" ng-model="hoiDap.TraLoi" ></textarea>
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <button type="submit" name="Save" class="btn btn-primary" >Lưu</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-8">
                        <div class="box box-primary">
                            <div class="box-header">
                                <h3 class="box-title">Danh Sách Câu Hỏi</h3>
                            </div>
                            <div class="box-body">
                                <table class="table table-bordered" >
                                    <thead>
                                        <?php
                                        foreach ($HoiDaps as $_hoidap) {
                                            $hoiDap = new \Model\News\HoiDap($_hoidap);
                                            ?>
                                            <tr>
                                                <th>
                                                    <div class="pull-right">
                                                        <a onclick="return confirm('Xóa Câu Hỏi Này?')" href="/mnews/xoacauhoi/<?php echo $hoiDap->Id; ?>" class="btn btn-danger" >
                                                            Xóa
                                                        </a>
                                                        <button ng-click="chonCauHoi('<?php echo $hoiDap->Id ?>', '<?php echo $hoiDap->CauHoi ?>', '<?php echo $hoiDap->TraLoi ?>')" class="btn btn-primary" >Chọn</button>
                                                    </div>
                                                    <strong ng-click="chonCauHoi('<?php echo $hoiDap->Id ?>', '<?php echo $hoiDap->CauHoi ?>', '<?php echo $hoiDap->TraLoi ?>')" ><?php echo $hoiDap->CauHoi ?></strong>
                                                    <p ng-click="chonCauHoi('<?php echo $hoiDap->Id ?>', '<?php echo $hoiDap->CauHoi ?>', '<?php echo $hoiDap->TraLoi ?>')" style="font-weight: normal;" >
                                                        <?php echo $hoiDap->TraLoi ?>
                                                    </p>
                                                </th>
                                            </tr>
                                            <?php
                                        }
                                        ?>

                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>
</div>