<?php
$dataNews = $NewsData;
?>
<div class="row " ng-controller="mnewsController" >
    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Bài Viết</h3>
            </div><!-- /.box-header -->
            <div class="box-body no-padding ">
                <div class=" " >
                    <table class="table table-hover table-bordered" id="dataTable" >
                        <thead>
                            <tr>
                                <th style="width: 50px">#</th>
                                <th >Tiêu Đề</th>
                                <th style="width: 250px">Danh Mục</th>
                            </tr>
                        </thead>
                        <tbody  >
                            <?php
                            foreach ($dataNews as $key => $value) {
                                $_news = new Model\news($value);
                                ?>
                                <tr>
                                    <td><?php echo $key + 1 ?></td>
                                    <td><a href="<?php echo Model\news::LinkDetail($_news->ID); ?>"  ><?php echo $_news->Name; ?></a></td>
                                    <td><?php echo $_news->PageID()->Name; ?></td>
                                </tr>

                                <?php
                            }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th style="width: 50px">#</th>
                                <th >Tiêu Đề</th>
                                <th style="width: 250px">Danh Mục</th>
                            </tr>
                        </tfoot>

                    </table>

                </div>
            </div><!-- /.box-body -->
        </div>
    </section>
</div>