<?php
$news = new \Model\news();
$Pages = new Model\pages();
$Tong = 0;
$indexPage = isset($_GET["indexPage"]) ? intval($_GET["indexPage"]) : 1;
$indexPage = max($indexPage, 1);
$Number = isset($_GET["Number"]) ? intval($_GET["Number"]) : 10;
$Name = isset($_GET["Name"]) ? $_GET["Name"] : "";
$opTimKiem["Name"] = $Name;
$DanhMuc = !empty($_GET["DanhMuc"]) ? $_GET["DanhMuc"] : "0";
$opTimKiem["DanhMuc"] = $DanhMuc;
$opTimKiem["hasalias"] = true;
$dataNews = $news->DanhSachTinPT($indexPage, $Number, $opTimKiem, $Tong);
?>
<div class="row ">
    <section class="col-md-12">
        <div class="box box-solid ">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Bài Viết</h3>
                <div class="box-tools">
                    <a class="btn btn-success" href="/mnews/linkimport/">import link</a>
                </div>
            </div>
            <div class="box-body no-padding ">
                <div class="">
                    <div class="d-flex">
                        <?php
                        \Model\PhanTrangForm::IndexPage($indexPage, ["id" => "indexPages", "onchange" => "FuncTimKiem()"])->render();
                        \Model\PhanTrangForm::TuKhoa($Name, ["id" => "TimKiemTuKhoa", "placeholder" => "Từ Khoá", "onchange" => "FuncTimKiem()"])->render();
                        \Model\PhanTrangForm::HienThi($Number, ["id" => "Number", "onchange" => "FuncTimKiem()"])->render();
                        Model\Pages\PagesService::ToSelectDequy(0, $dataPages);
                        $dataPages = ["0" => "Tất Cả"] + $dataPages;
                        \Model\PhanTrangForm::Select($DanhMuc, $dataPages, ["id" => "DanhMuc", "onchange" => "FuncTimKiem()"])->render();
                        ?>
                    </div>
                </div>
            </div>
            <div class=" ">
                <form action="">
                    <table class="table table-hover table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 50px">#</th>
                                <th style="width: 250px">Tiêu Đề</th>
                                <th>Link Gốc</th>
                                <th>Link Mới</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($dataNews) {
                                foreach ($dataNews as $key => $value) {
                                    $_news = new Model\news($value);
                            ?>
                                    <tr>
                                        <td class="text-center"><?php echo lib\Common::PhanTrangIndex($key, $Number, $indexPage); ?></td>
                                        <td><?php echo $_news->Name; ?></td>
                                        <td><?php echo $_news->Alias; ?></td>
                                        <td style="width: 40%;">
                                            <input class="form-control" value="<?php echo $_news->RedirectLink; ?>" type="text" name="link[<?php echo $_news->ID; ?>]">
                                        </td>
                                    </tr>
                            <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </form>
                <?php
                $TongTrang = ceil($Tong / $Number);
                $DuongDan = "/mnews/link/?indexPage=[i]&Name={$Name}&Number={$Number}&DanhMuc={$DanhMuc}";
                echo lib\Common::PhanTrang($TongTrang, $indexPage, $DuongDan);
                ?>
            </div>
        </div><!-- /.box-body -->
</div>
</section>
</div>
<script type="text/javascript">
    var FuncTimKiem = function() {
        var DuongDan = "/mnews/link/?indexPage={i}&Name={$Name}&Number={$Number}&DanhMuc={$DanhMuc}";
        var TuKhoa = $("#TimKiemTuKhoa").val();
        var Number = $("#Number").val();
        var DanhMuc = $("#DanhMuc").val();
        DuongDan = DuongDan.replace("{i}", 1);
        DuongDan = DuongDan.replace("{$Name}", TuKhoa);
        DuongDan = DuongDan.replace("{$Number}", Number);
        DuongDan = DuongDan.replace("{$DanhMuc}", DanhMuc);
        window.location.href = DuongDan;
    }
    $(function() {});
</script>