<?php
$ModelTabs = new Model\tags\tags();
$indexPage = isset($_GET['indexPage']) ? $_GET["indexPage"] : 1;
$pageNumber = isset($_GET['pageNumber']) ? $_GET["pageNumber"] : 20;
$total = 0;
$name = "";
$tabs = $ModelTabs->GetAllPT($name, $total, $indexPage, $pageNumber);
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Tabs</h3>
            <div class="box-tools">
                <a href="/tags/post/" class="btn btn-primary" ><i class="fa fa-plus" ></i></a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-bordered" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Alias</th>
                        <th>Link</th> 
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($tabs as $k => $mtabs) {
                        $_tabs = new Model\tags\tags($mtabs);
                        ?>
                        <tr>
                            <td><?php echo $k + 1 ?></td>
                            <td>
                                <a href="/tags/put/<?php echo $_tabs->Id ?>/" >
                                    <?php echo $_tabs->Name ?>
                                </a>
                            </td>
                            <td><?php echo $_tabs->Alias ?></td>
                            <td>
                                <a href="<?php echo $_tabs->LinkTags(); ?>" >
                                    Xem
                                </a>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Alias</th>
                        <th>Link</th>
                    </tr>
                </tfoot>
            </table>
            <?php
            $TongTrang = ceil($total / $pageNumber);
            $DuongDan = "/tabs/index/?indexPage=[i]&pageNumber={$pageNumber}";
            \lib\Common::PhanTrang($TongTrang, $indexPage, $DuongDan)
            ?>
        </div>
    </div>
</div>