<?php
$Minfor = new Module\minfor\Model\infor();
$infors =
    [
        "footer1",
        "footer2",
        "footer3",
        "footer4"
    ];
$Minfor->inforsInArray($infors);
?>
<div class="container-fluid">
    <div class="no-border-radius panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Cấu hình widgets</h3>
        </div>
        <div class="panel-body">
            <form action="" enctype="multipart/form-data" method="POST">
                <table class="table table-bordered">
                    <tbody>
                        <?php
                        foreach ($infors as $k => $_in) {
                            $_in = $Minfor->getbybyname($_in);
                            $_Config = $Minfor->_decode($_in["Config"]);
                            ?>
                            <tr>
                                <td>
                                    <?php echo $_in["Title"] ?>
                                    <br>
                                    __<?php echo $_in["Name"] ?>___
                                    <textarea id="Content<?php echo $_in["ID"] ?>" class="editor"
                                        name="Content[<?php echo $_in["ID"] ?>]"><?php echo $_in["Content"] ?></textarea>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </tbody>
                </table>
                <button name="Luu" class="btn btn-success pull-right" value="Luu" type="submit">Lưu</button>
            </form>

        </div>
    </div>
</div>