<div class="content-page">
    <div class=" page-404 mt-40" style="padding-bottom: 40px;">
        <div class="number">
            <?php echo http_response_code(); ?>
        </div>
        <div class="details">
            <h3>Oops!  You're lost.</h3>
            <p>
                We can not find the page you're looking for.<br>
                <a href="/" style="color: #0000ff;" >Return home</a> or try the search bar below.
            </p>
        </div>
        <div class="clearfix" ></div>
    </div>
    <div class="clearfix" ></div>
</div>