<h2 class="Title_widget" ng-show="{{title}}">{{title}}</h2>
<ul class="social-footer list-unstyled list-inline">
    <li class="btn-group btn-group-social">
        <a class="btn-social" href="__facebook___"><i class="fa fa-facebook"></i></a>
        <a class="btn-social" href="__google___"><i class="fa fa-google"></i></a>
        <a class="btn-social" href="__linkedin___"><i class="fa fa-linkedin"></i></a>
        <a class="btn-social" href="__twitter___"><i class="fa fa-twitter"></i></a>
        <a class="btn-social" href="__skype___"><i class="fa fa-skype"></i></a>
        <a class="btn-social" href="__youtube___"><i class="fa fa-youtube"></i></a>
    </li>
</ul>