<div class="TaiSaoChonChungToi_Content">
    <div class="title-tintuc">
        <h2>{{title}}</h2>
    </div>
    <div class="TaiSaoChonChungToi">
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-03.png" alt="Tinh năng">
            <h2>Đặt hàng & báo giá</h2>
            <h3>Trực tuyến</h3>
        </div>
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-02.png" alt="Tinh năng">
            <h2>Kiểm tra & phản hồi file in</h2>
            <h3>Trực tuyến</h3>
        </div>
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-01.png" alt="Tinh năng">
            <h2>Với 11 năm</h2>
            <h3>Trực tuyến</h3>
        </div>
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-04.png" alt="Tinh năng">
            <h2>Hơn 200.000 đơn</h2>
            <h3>Trực tuyến</h3>
        </div>
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-05.png" alt="Tinh năng">
            <h2>Đặt hàng & báo giá</h2>
            <h3>Trực tuyến</h3>
        </div>
        <div class="item">
            <img class="img img-responsive" src="/public/no-image.jpg" ng-src="/public/rubyv2/img/tinhnang-06.png" alt="Tinh năng">
            <h2>Đội ngũ giao hàng</h2>
            <h3>Trực tuyến</h3>
        </div>
    </div>
</div>