<?php
if (!isset($functionLayout))
    $functionLayout = new theme\qmts\functionLayout();

$view_theme = $functionLayout;
$Category = $data["Category"];
$Pages = intval($data["Pages"]);
$Pages = max($Pages, 1);


$cat = new \Model\Category();
$listCatID = [$Category->catID];
$cat->AllCategoryByParentID([$Category->catID], $listCatID);
$product = new \Model\Products();
//var_dump($listCatID);
$number = 21;
$sum = 0;
$DSProduct = $product->ProductsByCatID($listCatID, $Pages, $number, $sum);
?>

<!-- view-product-list-->
<div style="margin-top: 0px;" id="view-product-list" class="container view-product-list">
    <h2 class="page-heading">
        <span class="page-heading-title"><?php echo $Category->catName; ?></span>
    </h2>

    <div class="row product-list grid">
        <?php
        if ($DSProduct)
            foreach ($DSProduct as $_Poroduct) {
                ?>
                <div class="col-xs-6 col-sm-4">
                    <?php
                    $view_theme->product($_Poroduct);
                    ?>
                </div>
                <?php
            }
        ?>

    </div>
    <!-- ./PRODUCT LIST -->
</div>
<!-- ./view-product-list-->
<div class="sortPagiBar container ">
    <div class="bottom-pagination">
        <nav>
            <?php
            $TongTrang = ceil($sum / $number);
            echo $product->PhanTrang($TongTrang, $Pages, $Category->Link . "/pages-[i]");
            ?>

        </nav>
    </div>
    <div class="hidden show-product-item">
        <select name="">
            <option value="">Show 21</option>
            <option value="">Show 42</option>
            <option value="">Show 63</option>
            <option value="">Show 84</option>
        </select>
    </div>
    <div class="hidden sort-product">
        <select>
            <option value="">Product Name</option>
            <option value="">Price</option>
        </select>
        <div class="sort-product-icon">
            <i class="fa fa-sort-alpha-asc"></i>
        </div>
    </div>
    <div class="clearfix" ></div>

</div>