<?php
$adv = new Model\adv();
$DanhMucDoiTac = [];
$PageGioiThieu = new Model\pages(theme\ThemeConfig::getThemConfigByKey(\theme\ThemeConfig::GioiThieu));
$HomeCategory = theme\ThemeConfig::getThemConfigByKey(\theme\ThemeConfig::HomeCategory);
$homeslide = $adv->AdvsByGroup("homeslide", FALSE);
$DanhMucDoiTac = $adv->AdvsByGroup("DoiTac", FALSE);
$KhachHangNoiVeChungToi = $adv->AdvsByGroup("KHNVCT", FALSE);
?>
<section class="mainslide">
    <div id="carouselExampleIndicators1" class="carousel slide" data-ride="carousel"  >
        <div class="carousel-inner" role="listbox">
            <?php
            if ($homeslide)
                foreach ($homeslide as $keyword => $value) {
                    $_adv = new Model\adv($value);
                    ?>
                    <div class="carousel-item <?php echo $keyword == 0 ? 'active' : '' ?>" style="background-image: url('<?php echo $_adv->Urlimages; ?>')"  >
                    </div>
                    <?php
                }
            ?>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
    <?php
    if ($DanhMucDoiTac) {
        ?>
        <div class="danhSachDoiTac bg-dark60 p-2 " >
            <div class="container " >
                <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":8}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
                    <?php
                    foreach ($DanhMucDoiTac as $key => $value) {
                        $_news = new Model\adv($value);
                        ?>
                        <div class="item ">
                            <a href="<?php echo $_news->Link; ?>">
                                <img class="" src="<?php echo $_news->Urlimages; ?>" alt="<?php echo $_news->Name; ?>">
                            </a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <?php
    }
    ?>

</section>


<section class="Content mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-justify">
                <?php
                echo $PageGioiThieu->Content;
                ?>
            </div>
        </div>
    </div>
</section>
<section class="">
    <div class=" ">
        <div class=" ">
            <div>
                <div class="bg-theme taisaochonchungtoi p-3">
                    <div class="container">
                        <div class="row p-4">
                            <div class="col-md-8 item">
                                <h2 class="title taisaochonchungtoi-title text-center">Gọi Cho Chúng Tôi Để Được Tư Vấn</h2>
                            </div>
                            <div class="col-md-4 item">
                                <h2 class="title fs-4 taisaochonchungtoi-title text-center">__lblHotline___: <a href="tel:__Hotline___" style="color: #000;" class="" >__Hotline___</a>  </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
if ($HomeCategory) {
//    var_dump($HomeCategory[0]["Id"]);
    $Page1 = new Model\pages($HomeCategory[0]["Id"]);
    unset($HomeCategory[0]);
    ?>
    <section class="BaiVietNoiBat bg-gray p-5 " >
        <div class="container">
            <div class="row ">
                <div class="col-md-12">
                    <h2 class="d-none text-center fw-bold fs-3 p-3" >Dịch Vụ</h2>
                </div>

                <div class="col-md-6">
                    <div class="card border-radius-0 BaiVietNoiBat-Main ">
                        <a href="<?php echo $Page1->linkPagesCurent(); ?>" >
                            <img onerror="this.src='/public/LuatMaiThiKimSa/images/card-img.png'" class="card-img-top" src="<?php echo $Page1->Urlimages; ?>" alt="<?php echo $Page1->Name; ?>">
                            <div class="card-body">
                                <h5 class="card-title"><?php echo $Page1->Name; ?></h5>
                                <hr style="border-bottom: 1px solid #fff;"  >
                                <p class="card-text"><?php echo $Page1->Summary; ?></p>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <?php
                        if ($HomeCategory) {
                            $class = ["BaiVietNoiBat2", "BaiVietNoiBat3", "BaiVietNoiBat3", "BaiVietNoiBat3", "BaiVietNoiBat3", "BaiVietNoiBat3"];
                            foreach ($HomeCategory as $k => $value) {

                                $page2 = new Model\pages($value["Id"]);
                                ?>
                                <div class="<?php echo $k == 1 ? 'col-md-12' : 'col-md-6'; ?>  mb-4">
                                    <a href="<?php echo $page2->linkPagesCurent() ?>"  >
                                        <div class="card border-radius-0 <?php echo $class[$k - 1]; ?>">
                                            <img  class="card-img-top" onerror="this.src='/public/LuatMaiThiKimSa/images/card-img.png'" src="<?php echo $page2->Urlimages ?>" alt="<?php echo $page2->Name ?>">
                                            <div class="">
                                                <h5 class="card-title"><?php echo $page2->Name ?></h5>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php
}
?>

<?php
echo \theme\kimsanews\functionLayout::TaiSaoChonChungToi;
echo \theme\kimsanews\functionLayout::ChungToiLaAi;
?>

<section class="bg-dark" >
    <div class="container">
        <h2 class="p-3 fs-3 text-center color-while" >Khách Hàng Nói Về Chúng Tôi</h2>
        <div id="carouselExampleIndicators2" class="NhanXetCuaKhacHang carousel slide" data-ride="carousel"  >
            <div class="carousel-inner" role="listbox">
                <?php
                foreach ($KhachHangNoiVeChungToi as $k => $value) {
                    $_news = new Model\adv($value);
                    ?>
                    <div class="carousel-item <?php echo $k == 0 ? 'active' : '' ?>">

                        <div class="carousel-caption">
                            <h5><?php echo $_news->Name ?></h5>
                            <p><blockquote><?php echo $_news->Content; ?></blockquote></p>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
    </div>

</section>
<section>
    <div class="container p-4" >
        <div class="owl-custom DanhSachDoiTac owl-carousel owl-theme" data-responsive='{"380":{"items":2},"600":{"items":4},"1000":{"items":5}}'  data-dots-each="true" data-dots="false" data-loop="true" data-nav="true" data-margin="10" >
            <?php
            $DSTinMoiNhat = $functionLayout->DanhSachTinMoiNhat();
            if ($DSTinMoiNhat)
                foreach ($DSTinMoiNhat as $value) {
                    $_news = new Model\news($value);
                    ?>
                    <div  class="card TinNoiBat item ">
                        <a style="" href="<?php echo $_news->linkNewsCurent(); ?>">
                            <img src="<?php echo $_news->UrlHinh; ?>" onerror="this.src='/public/no-image.jpg'" alt="<?php echo $_news->Name; ?>">
                        </a>
                        <div class="card-body p-2" >
                            <a href="<?php echo $_news->linkNewsCurent(); ?>" >
                                <?php echo $_news->Name; ?>
                            </a>
                        </div>
                    </div>
                    <?php
                }
            ?>
        </div>
    </div>
</section>