<?php
$bk = new theme\backend\backend();
$a = new Model_Adapter();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Quản trị</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?php
        $bk->head();
        ?>
        <link rel="shortcut icon" href="/public/no-image.jpg" />
        <link href="/public/home/assets/lib/owl.carousel/owl.carousel.css" rel="stylesheet" type="text/css"/>
        <script src="/public/partials/loaderpartials/mproduct/mproductconfig.js" type="text/javascript" ></script>
    </head>
    <body class="hold-transition   skin-blue sidebar-mini" ng-cloak="TRUE" ng-app="rootApp"  >
        <div class="wrapper">
            <?php
            $bk->Menu();
            ?>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper" style="padding: 0px;" >
                <section class="content" style="padding: 0px;" >
                    <?php include $Content; ?>
                </section>
            </div>
            <?php
            $bk->Footer();
            ?>
        </div><!-- ./wrapper -->
        <?php
        $bk->js();
        ?>

        <script src="/public/home/assets/lib/owl.carousel/owl.carousel.min.js" type="text/javascript"></script>
        <script src="/public/admin/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>
        <script type="text/javascript" >

            $(document).ready(function() {
                $(".select2").select2();

                $(".owl-carousel").each(function(index, el) {
                    var config = $(this).data();
                    config.navText = ['', ''];
                    config.smartSpeed = "300";
                    if ($(this).hasClass('owl-style2')) {
                        config.animateOut = "fadeOut";
                        config.animateIn = "fadeIn";
                    }
                    $(this).owlCarousel(config);
                });
                $(".editor").each(function(index, el) {
                    CKEDITOR.replace($(this).attr("id"), {
                        height: "500px"
                    });
                });
                $('.editorMini').each(function() {
                    var id = $(this).attr("id");
                    CKEDITOR.replace(id, {
                        toolbar: [
                            {name: 'document', items: ['Source', ]},
                            {name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat']}, {name: 'links', items: ['Link', 'Unlink', 'Anchor']},
                            {name: 'insert', items: ['Image', 'Smiley', 'SpecialChar', ]},
                        ],

                    });
                });

            });
        </script>
    </body>
</html>
