<?php
include "LoadTheme.php";
echo " ";
flush();
?>
<!DOCTYPE html>
<html lang="vi" ng-cloak="TRUE" ng-app="rootApp"   ng-controller="homeController" >
    <head>
        <?php
        $functionLayout->gethtml();
        flush();
        ?>
    </head>
    <body class="corporate">

        <?php
        $functionLayout->header();
        $functionLayout->Menu();
        ?>
        <div class="container"  >
            <div class="row"  >
                <div class="col-md-8"  >
                    <?php
                    include $Content;
                    ?>
                </div>
                <div class="col-md-4" >
                    <?php
                    $functionLayout->right();
                    ?>

                </div>
            </div>
        </div>


        <?php
        $functionLayout->footer();
        $functionLayout->js();
        ?>
    </body>


</html>
<?php
$functionLayout->DeCodeHTML();
flush();
?>