<?php
$adv = new \Model\adv();
$_homeslide = $adv->AdvsByGroup("homeslide", FALSE);
$_homeslideClass = ["carousel-item-eight", "carousel-item-nine", "carousel-item-ten"];
$HomeCategory = \theme\ThemeConfig::getThemConfigByKey(\theme\ThemeConfig::HomeCategory);
?>
<div class="col-sm-8" >
    <div class="page-slider margin-bottom-20">
        <div id="carousel-example-generic" class="carousel slide carousel-slider">
            <!-- Indicators -->
            <ol class="carousel-indicators carousel-indicators-frontend">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <?php
                foreach ($_homeslide as $k => $adv) {
                    $_adv = new \Model\adv($adv);

                    $classK = $k % 3;
                    ?>
                    <div style="background-image: url('<?php echo $_adv->Urlimages; ?>')"
                         class="item  <?php
                         echo $_homeslideClass[$classK];
                         echo $k == 0 ? ' active' : ''
                         ?>"  >
                    </div>
                    <?php
                }
                ?>

            </div>

            <!-- Controls -->
            <a class="left carousel-control carousel-control-shop carousel-control-frontend" target="_self" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            <a class="right carousel-control carousel-control-shop carousel-control-frontend" target="_self" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</div>
<div class="col-md-4" >
    <div role="tabpanel" class="tabTheme" >
        <!-- Nav tabs -->
        <ul class=" nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#tabhome" aria-controls="tabhome" role="tab" data-toggle="tab">Bài Viết Mới</a>
            </li>
            <li role="presentation">
                <a href="#tabhome1" aria-controls="tabhome1" role="tab" data-toggle="tab">Văn bản pháp luật</a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="tabhome">
                <div class="col-md-12" >
                    <ul class="list-news-right" >
                        <li ng-repeat="news in _baivietmoinhat" >
                            <a title="{{news.Name}}" href="{{news.Link}}">
                                {{news.Name}}
                            </a>
                        </li>
                    </ul>
                </div>


            </div>
            <div role="tabpanel" class="tab-pane" id="tabhome1">
                <div class="col-md-12" >
                    <ul class="list-news-right" >
                        <li ng-repeat="news in _vanbanphapluat.News" >
                            <a title="{{news.Name}}" href="{{news.Link}}">
                                {{news.Name}}
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="clearfix" ></div>
        </div>
    </div>




</div>
<div class="clearfix" style="padding-bottom: 15px;" ></div>
<div class="col-sm-8" >
    <div class="panel panel-theme">
        <div class="panel-heading">
            <h3 class="panel-title">Bài Viết Nổi Bật</h3>
        </div>
        <div class="panel-body" style="min-height: 384px">
            <div class="col-md-6" >
                <img onerror="this.src='/public/lawkimsa/Images/h1.jpg'" class="img img-responsive" src="{{_BaiVietNoiBat[0].UrlHinh}}" alt="{{_BaiVietNoiBat[0].Name}}"/>
                <a href="{{_BaiVietNoiBat[0].Link}}" >
                    <h2 class="newstitle" >{{_BaiVietNoiBat[0].Name}}</h2>
                </a>
                <p style="" >{{_BaiVietNoiBat[0].NgayDang}}</p>
                <p style="height: 4em;overflow: hidden;line-height: 1em;text-align: justify;" >{{_BaiVietNoiBat[0].Summary}}</p>
            </div>
            <div class="col-md-6" >
                <ul class="list-news-right" >
                    <li ng-show="$index > 0" ng-repeat="newsNoiBat in  _BaiVietNoiBat" >
                        <a href="{{newsNoiBat.Link}}">{{newsNoiBat.Name}}</a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</div>
<div class="col-md-4" >
    <div class="panel panel-theme" ng-init="TaiSaoChonChungToi()" >
        <div class="panel-heading">
            <h3 class="panel-title">{{_TaiSaoChonChungToi.Pages.Name}}</h3>
        </div>
        <div class="panel-body" style="min-height: 380px" >
            <div class=" service-box margin-bottom-40">
                <div class="  " ng-repeat="newsTaisao in _TaiSaoChonChungToi.News" >
                    <div class="service-box-heading">
                        <em><i class="fa fa-check gold" ></i></em>
                        <strong><span>{{newsTaisao.Name}}</span></strong>
                    </div>
                    <p>{{newsTaisao.Summary}}
                    </p>
                </div>
                <!--                <div class=" ">
                                    <div class="service-box-heading">
                                        <em><i class="fa fa-check gold"></i></em>
                                        <strong><span>Chính Xác</span></strong>
                                    </div>
                                    <p>Lorem ipsum dolor sit amet, dolore eiusmod
                                        quis tempor incididunt ut et dolore Ut veniam
                                    </p>
                                </div>
                                <div class=" ">
                                    <div class="service-box-heading">
                                        <em><i class="fa fa-check gold"></i></em>
                                        <strong><span>Hiệu Quả</span></strong>
                                    </div>
                                    <p>Lorem ipsum dolor sit amet, dolore eiusmod
                                        quis tempor incididunt ut et dolore Ut veniam
                                    </p>
                                </div>-->
            </div>
        </div>
    </div>
</div>

<?php
$page = new \Model\pages();
foreach ($HomeCategory as $key => $value) {
//    $item = new \Model\pages($page->PagesById($value["Id"]));
    if ($value["Type"] == "Pages") {
        $item = new \Model\pages($page->PagesById($value["Id"], FALSE));
    }
    $news = $item->getNewsMoi();
    $_news = new \Model\news($news[0]);
    unset($news[0]);
    ?>
    <div class="col-md-6" >
        <div class="panel panel-theme">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $item->Name ?></h3>
            </div>
            <div class="panel-body" style="min-height: 450px" >
                <div class="row" >
                    <div class="col-md-4" >
                        <a href="<?php echo $_news->linkNewsCurent(); ?>"  >
                            <img class="img img-responsive"
                                 src ="<?Php echo $_news->UrlHinh; ?>"
                                 onerror="this.src='/public/lawkimsa/Images/h1.jpg'" alt="<?Php echo $_news->Name; ?>"/>
                        </a>
                    </div>
                    <div class="col-md-8" >
                        <a href="<?php echo $_news->linkNewsCurent(); ?>"  >
                            <h2 class="newstitle text-justify" ><?Php echo $_news->Name; ?></h2>
                        </a>
                        <p><?Php echo $_news->Name; ?></p>
                    </div>
                </div>
                <div class="col-md-12" >
                    <hr>
                    <ul class="list-news-right" >
                        <?php
                        foreach ($news as $k => $value) {
                            $_new = new \Model\news($value);
                            ?>
                            <li>
                                <a href="<?php echo $_new->linkNewsCurent() ?>">
                                    <?php echo $_new->Name; ?>
                                </a>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>

                </div>

            </div>
        </div>
    </div>
    <?php
}
?>