<?php
$_News = new Model\news($data["news"]);
$_Pages = new Model\pages($data["pages"]);
?>
<!-- Product -->
<div class="Main-Content" >
    <div >
        <h2 class="text-bold"  ><?php echo $_News->Name ?></h2>
        <?php echo $_News->Content; ?>
    </div>
</div>
<hr>
<h3>Bài Viết Liên Quan</h3>
<ul>
    <?php
    $newsLienQuan = $_News->BaiVietLienQuan();
    if ($newsLienQuan)
        foreach ($newsLienQuan as $key => $value) {
            $_news = new \Model\news($value);
            ?>
            <li><a href = "<?php echo $_news->linkNewsCurent(); ?>" > <?php echo $_news->Name; ?></a></li>
            <?php
        }
    ?>
</ul>