<?php
$view_theme = new \theme\qmts\functionLayout();
$_Pages = new \Model\pages($data["pages"]);
$Model_News = new \Model\news();
$newsByPage = $Model_News->NewsByPagesLimitNumber($_Pages->idPa, 9, FALSE);
$_new = $newsByPage[0];
if ($_new)
    $_new = new Model\news($_new);

unset($newsByPage[0]);
?>
<div  >

    <div class="panel panel-theme">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $_Pages->Name ?></h3>
        </div>
        <div class="panel-body">
            <?php
            if ($_new) {
                ?>
                <div class="row" >
                    <div class="col-md-4" >
                        <a href="<?php echo $_new->linkNewsCurent(); ?>"  >
                            <img onerror="this.src='/public/lawkimsa/Images/h1.jpg'" class="img img-responsive" src="<?php echo $_new->UrlHinh ?>" alt="<?php echo $_new->Name ?>"/>
                        </a>
                    </div>
                    <div class="col-md-8" >
                        <a href="<?php echo $_new->linkNewsCurent(); ?>" class="" >
                            <h2 class="newstitle text-justify" ><?php echo $_new->Name ?></h2>
                        </a>
                        <p><span><?php echo $_new->NgayDang() ?></span>  </p>
                        <p><?php echo $_new->Summary(); ?></p>
                    </div>
                </div>
                <?php
            }
            ?>

            <div class="col-md-12" >
                <hr>
                <ul class="list-news-right" >
                    <?php
                    if ($newsByPage)
                        foreach ($newsByPage as $_news) {
                            $news = new \Model\news($_news);
                            ?>
                            <li>
                                <a href="<?php echo $news->linkNewsCurent(); ?>">
                                    <?php echo $news->Name; ?>
                                </a>
                            </li>

                            <?php
                        }
                    ?>
                </ul>
            </div>
        </div>
    </div>

</div>

