<?php
if (!isset($functionLayout)) {
    $functionLayout = new theme\noithathoaphatgiagoc\functionLayout();
//    $view_theme = new \theme\noithathoaphatgiagoc\functionLayout();
}
$_Pages = new \Model\pages($data["pages"]);
$Model_News = new \Model\news();
$newsByPage = $Model_News->NewsByPagesLimitNumber($_Pages->idPa, 9, FALSE);
?>
<!-- view-product-list-->
<div  >
    <div  >
        <div id="product-detail" class="text-justify" >
            <?php echo $_Pages->Content ?>
        </div>
        <div class="clearfix" ></div>
    </div>
</div>
<!-- ./view-product-list-->
