
<div class="row"  ng-controller="mpageController">
    <section class="col-md-12" >
        <div class="box box-solid ">
            <div class="box-header">
                <a href="/mpage/addpage/" class="btn pull-right btn-success"  >Thêm</a>
                <h3 class="box-title">Quản Lý Bài Viết</h3>

            </div><!-- /.box-header -->
            <div class="box-body no-padding ">
                <div class="table-responsive" >

                    <table class="table table-bordered  " id="dataTable" >
                        <thead>
                            <tr>
                                <th></th>
                                <th style="width: 50px">#</th>
                                <th >Tên Trang</th>
                                <th style="width: 150px">Danh mục cha</th>
                                <th style="width: 100px">Hiển Thị</th>
                                <th style="width: 100px">Loại Trang</th>
                            </tr>
                        </thead>
                        <tbody >
                            <tr ng-repeat="itemPage in  _Pages"  >
                                <td style="width: 150px;" >
                                    <a class="btn btn-sm btn-primary" href="/mpage/editpage/{{itemPage.idPa}}" >Sửa</a>
                                    <span class="bakco-modaldelete" ng-init="modaldeleteInit('Xóa', 'Thông Báo', 'Bạn có muốn xóa trang này', '/mpage/deletepage/' + itemPage.idPa, itemPage.idPa)" ></span>
                                </td>
                                <td>{{itemPage.idPa}}</td>
                                <td>
                                    <a ng-show="itemPage.Type == 1" href="/mnews/newsbypages/{{itemPage.idPa}}" >{{itemPage.Name}}</a>
                                    <a ng-show="itemPage.Type != 1" href="/mpage/editpage/{{itemPage.idPa}}" >{{itemPage.Name}}</a>
                                </td>
                                <td>
                                    <span ng-show="itemPage.idGroup == 0">{{itemPage.idGroupName}}</span>
                                    <a ng-show="itemPage.idGroup > 0" href="/mpage/editpage/{{itemPage.idGroup}}" >{{itemPage.idGroupName}}</a>
                                </td>
                                <td>
                                    {{itemPage.isShow==0?"Ẩn":"Hiện"}}
                                </td>
                                <td>{{itemPage.TypeName}}</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th> </th>
                                <th>#</th>
                                <th>Tên Trang</th>
                                <th>Nhóm</th>
                                <th>Hiển Thị</th>
                                <th>Loại Trang</th>
                            </tr>
                        </tfoot>

                    </table>

                </div>
            </div><!-- /.box-body -->
        </div>
    </section>
</div>