
<div class="container-fluid">
    <section class="" >
        <div class="box box-solid ">
            <div class="box-header bg-green">
                <i class="fa fa-book"></i>
                <h3 class="box-title">Danh Mục Sản Phẩm ({{ListCategory.length}})</h3>
                <div class="box-tools">
                    <a class="btn btn-sm btn-primary" data-toggle="modal" href='#modal-id'>Thêm Danh Mục</a>
                    <a class="btn btn-sm btn-primary" data-toggle="modal" href='#SapXep'>Sắp Xếp</a>
                </div>
            </div>
            <div class="box-body no-padding ">
                <div class="" ng-controller="listcategorysController" >
                    <form action="/mcategory/editorderby/" method="POST" enctype="multipart/form-data" >
                        <div class="modal fade" id="SapXep">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">Modal title</h4>
                                    </div>
                                    <div class="modal-body">
                                        <ul class="todo-list ui-sortable">
                                            <li  ng-repeat="item in ListCategory" class="" style="">
                                                {{$index + 1}}
                                                <span class="handle ui-sortable-handle">
                                                    <i class="fa fa-ellipsis-v"></i>
                                                    <i class="fa fa-ellipsis-v"></i>
                                                </span>
                                                <input type="hidden" value="{{$index}}" name="orderBy[{{item.catID}}]">
                                                {{item.catName}}
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="submit" name="saveOrderBy" class="btn btn-primary">Lưu</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="modal fade" id="modal-id">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">Danh Mục</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="box-body bakco-formcategory" ng-init="formcategoryInit(_CategoryDetail.catID, true)" >
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 " >
                        <table class="table " >
                            <tr>
                                <th><input class="form-control" ng-model="Timkiem.catName" placeholder="Tên Danh Mục" ></th>
                                <th>
                                    <select ng-model="Timkiem.parentCatID" class="form-control select2" >
                                        <option value="" >Tất cả</option>
                                        <option ng-repeat="item in ListCategory" value="{{item.catID}}" >{{item.catName}}</option>
                                    </select>

                                </th>
                            </tr>
                        </table>
                        <div class="clearfix" ></div>
                        <div class="  table-responsive"  >
                            <table class="table table-bordered table-hover"  >
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Mã Danh Mục</th>
                                        <th>Tên Danh Mục</th>
                                        <th>Tên Không Dấu</th>
                                        <th>Tên Danh Mục Cha</th>
                                        <th>Số Thứ Tự</th>
                                        <th>Ẩn Hiển</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody  style="height: 500px;" >
                                    <tr ng-repeat="item in ListCategory| filter : Timkiem" >
                                        <td>{{$index + 1}}</td>
                                        <td>
                                            {{item.catID}}
                                        </td>
                                        <td>
                                            <a href="/mproduct/index/{{item.catID}}"  ><b>{{item.catName}}</b></a>
                                        </td>
                                        <td><b>{{item.Path}}</b>

                                        </td>
                                        <td>
                                            <a ng-show="item.parentCatID != 0" href="/mcategory/detail/{{item.parentCatID}}"  >{{showNameCategory(item.parentCatID)}}</a>
                                            <a ng-show="item.parentCatID == 0" >{{showNameCategory(item.parentCatID)}}</a>
                                        </td>

                                        <td>{{item.Serial}}</td>
                                        <td>{{item.Public==1?"Hiện":"Ẩn"}}</td>
                                        <td>
                                            <div  class="btn-group btn-group-sm" >
                                                <a class="btn btn-sm btn-danger xoa" onclick="return confirm('Xóa Danh Mục Này?')" href="/mcategory/deleteid/{{item.catID}}" >Delete</a>
                                                <a class="btn btn-primary" data-toggle="modal" ng-click="selectCategory(item.catID)" href='#modal-id'>Chọn</a>
                                                <a class="btn btn-sm btn-success" type="button" href="/mcategory/copy/{{item.catID}}" >Copy</a>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>STT</th>
                                        <th>Mã Danh Mục</th>
                                        <th>Tên Danh Mục</th>
                                        <th>Tên Không Dấu</th>
                                        <th>Tên Danh Mục Cha</th>
                                        <th>Số Thứ Tự</th>
                                        <th>Ẩn Hiển</th>
                                        <th></th>
                                    </tr>
                                </tfoot>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>