<?php

use Model\Products;
use Model\ProductsForm;

$_product = $data["p"];
$Product = new Products($_product);
$productsForm = new ProductsForm((array) $Product);
?>
<ol class="breadcrumb">
    <li><a href="/backend/">Tranh chủ</a></li>
    <li><a href="/mproduct/index">Danh Sản Phẩm</a></li>
    <li>Copy</li>
</ol>
<form action="" method="POST" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="box box-solid ">
            <div class="box-header bg-blue">
                <h3 class="box-title">Thêm Sản Phẩm</h3>
            </div>
            <div class="box-body">
                <div class="row">

                    <div class="col-md-9">
                        <?php
                        $productsForm->Id()->render();
                        $productsForm->Name()->renderHTML();
                        $productsForm->Summary()->renderHTML();
                        $productsForm->Content()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-3">
                        <div class="">
                            <div class="col-md-8">
                                <div class="row">
                                    <?php
                                    $productsForm->Price()->renderHTML();
                                    ?>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="row">
                                    <?php
                                    $productsForm->DonViTinh()->renderHTML();
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                <label>Chọn Hình</label>
                                <label style="border: 1px solid #000;background-color: rgba(0, 0, 0, 0.34);color: #fff;text-align: center;position: relative;height: 105px;display: block;z-index: 2">
                                    <input style="display: none" onclick="BrowseServer('Images:/images/', 'UrlHinh')" type="button" name="btnChonFilBrowseServere" id="btnChonFile" value="Chọn File" />
                                    <div class="HinhChon" style="position: absolute;top: 0px;z-index: 1">
                                        <img id="HinhQuanCao" src="<?php echo $Product->UrlHinh() ?>" style="height: 100px;max-width: 200px">
                                    </div>
                                </label>
                                <div style="clear: both"></div>
                                <?php
                                $productsForm->UrlHinh()->render();
                                ?>
                            </div>
                        </div>
                        <?php
                        $productsForm->catID()->renderHTML();
                        $productsForm->isShow()->renderHTML();
                        $productsForm->lang()->renderHTML();
                        ?>
                        <div class="form-group" style="margin-top: 15px;">
                            <button name="LuuSanPham" style="min-width: 100px" class="btn btn-primary" type="submit">Lưu Sản Phẩm</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>