<?php

use Datatable\Table;
use Model\FormCommon;
use Model\FormRender;
use Model\Products;

$table = new Table(["rows" => $DataTable->rows, "columns" => $DataTable->columns], Products::class);
$table->setPropTable(
    [
        "table" => ["class" => "table table-border"],
        "thead" => ["class" => "bg-primary"]
    ]
);
$params =  $DataTable->params ?? [];
// var_dump($params);
?>
<ol class="breadcrumb">
    <li><a href="/backend/">Trang Chủ</a></li>
    <li>Danh Sách Sản Phẩm</li>
</ol>
<div class="container-fluid ">
    <section class="">
        <div class="box box-solid ">
            <div class="box-header bg-blue">
                <i class="fa fa-list-ol"></i>
                <h3 class="box-title">Danh Sách Sản Phẩm</h3>
                <div class="box-tools">
                    <a href="/mproduct/addproduct/" class="btn btn-success">Thêm Sản Phẩm</a>
                </div>
            </div>
            <div class="box-body connectedSortable">
                <div>
                    <form action="/mproduct/index/" method="get">
                        <div class="input-group  " style="width: 250px;" >
                            <?php
                            FormCommon::Hidden("indexPage", 1)->render();
                            FormCommon::Hidden("pageNumber",  $DataTable->pageNumber ?? 10)->render();
                            FormCommon::Name("", "Name", $params["Name"] ?? "")->render();
                            ?>
                            <div class="input-group-btn">
                                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>

                    <?php
                    $table->RenderHtml();
                    echo $table->PaginationWidthData((array)$DataTable, "/mproduct/index/");
                    ?>
                </div>
            </div>
        </div>
    </section>
</div>