<!DOCTYPE html>
<?php

use theme\rubyv2\functionLayout;
?>
<html lang="vi" ng-cloak="TRUE" ng-app="rootApp"   ng-controller="homeController"  >
    <head>
        <?php
        functionLayout::head();
        ?>
    </head>
    <body class="corporate">

        <!-- END TOP BAR -->
        <!-- BEGIN HEADER -->
        <?php
        functionLayout::header();
        ?>
        <!-- Header END -->
        <!-- BEGIN SLIDER -->
        <div class="page-slider margin-bottom-40">
            <div id="carousel-example-generic" class="carousel slide carousel-slider">
                <!-- Indicators -->
                <ol class="carousel-indicators carousel-indicators-frontend">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <!-- First slide -->
                    <div style="background-color: #103852;background: url('/public/bdsltp/public/images/banner/banner2.jpg')" class="item active">
                        <div class="container">
                            <div class="carousel-position-six text-uppercase text-center">
                                <h2 class="margin-bottom-20 animate-delay carousel-title-v5" data-animation="animated fadeInLeft">
                                    Thiết Kế Và Thi Công <br/>
                                    <span class="carousel-title-normal">Hotline: 0123456789</span>
                                </h2>
                                <p class="carousel-subtitle-v5 border-top-bottom margin-bottom-30" data-animation="animated fadeInDown">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                </p>

                                <a class="carousel-btn-green" href="#" data-animation="animated fadeInRight">Xem ngay</a>
                            </div>

                        </div>
                    </div>
                    <div style="background-color: #103852;background: url('/public/bdsltp/public/images/banner/banner2.jpg')" class="item ">
                        <div class="container">
                            <div class="carousel-position-six text-uppercase text-center">
                                <h2 class="margin-bottom-20 animate-delay carousel-title-v5" data-animation="animated fadeInDown">
                                    Thiết Kế Và Thi Công <br/>
                                    <span class="carousel-title-normal">Hotline: 0123456789</span>
                                </h2>
                                <p class="carousel-subtitle-v5 border-top-bottom margin-bottom-30" data-animation="animated fadeInDown">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                </p>

                                <a class="carousel-btn-green" href="#" data-animation="animated fadeInUp">Xem ngay</a>
                            </div>

                        </div>
                    </div>
                    <div style="background-color: #103852; background: url('/public/bdsltp/public/images/banner/banner2.jpg')" class="item ">
                        <div class="container">
                            <div class="carousel-position-six text-uppercase text-center">
                                <h2 class="margin-bottom-20 animate-delay carousel-title-v5" data-animation="animated fadeInDown">
                                    Thiết Kế Và Thi Công <br/>
                                    <span class="carousel-title-normal">Hotline: 0123456789</span>
                                </h2>
                                <p class="carousel-subtitle-v5 border-top-bottom margin-bottom-30" data-animation="animated fadeInDown">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                </p>

                                <a class="carousel-btn-green" href="#" data-animation="animated fadeInUp">Xem ngay</a>
                            </div>

                        </div>
                    </div>

                </div>

                <!-- Controls -->
                <a class="left carousel-control carousel-control-shop carousel-control-frontend" href="#carousel-example-generic" role="button" data-slide="prev">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                </a>
                <a class="right carousel-control carousel-control-shop carousel-control-frontend" href="#carousel-example-generic" role="button" data-slide="next">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <!-- END SLIDER -->

        <div class="main">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="">
                            <div class="row margin-bottom-30">
                                <!-- BEGIN INFO BLOCK -->
                                <div class="col-md-6">
                                    <h2 class="no-top-space">Lê Thuận Phát</h2>
                                    <p>
                                        Công ty tư vấn thiết kế biệt thự Lê Thuận Phát được thành lập với mong muốn trở thành địa chỉ tin cậy, chuyên sâu về lĩnh vực thiết kế và xây dựng nhà ở, biệt thự cùng những hạng mục thi công hoàn thiện, nội thất khác trong công trình. Chúng tôi là những chuyên gia tiên phong trong các giải pháp thiết kế xây dựng nhà ở dân dụng tại Việt Nam.
                                        <br>
                                        Tên thương hiệu Kiến An thể hiện khát vọng của những người sáng lập mong muốn theo đuổi đến tận cùng các giá trị về cái đẹp trong kiến trúc và sự đảm bảo chất lượng, an toàn chi phí cho chủ đầu tư.
                                    </p>
                                    <!-- BEGIN LISTS -->
                                    <div class="row front-lists-v1">
                                        <div class="col-md-12" >
                                            <h3>Thông Tin Cần Biết</h3>
                                        </div>
                                        <div class="col-md-6">
                                            <ul class="list-unstyled margin-bottom-20">
                                                <li><i class="fa fa-check"></i> Thiết Kế Nhà</li>
                                                <li><i class="fa fa-check"></i> Thi Công Nhà Ở</li>
                                                <li><i class="fa fa-check"></i> Bán BĐS</li>
                                            </ul>
                                        </div>
                                        <div class="col-md-6">
                                            <ul class="list-unstyled">
                                                <li><i class="fa fa-check"></i> Tư Vấn Thiết Kế</li>
                                                <li><i class="fa fa-check"></i> Tư Tấn Thi Công </li>
                                                <li><i class="fa fa-check"></i> Hỗ Trợ Nhiệt Tình</li>
                                            </ul>
                                        </div>
                                    </div>
                                    <!-- END LISTS -->
                                </div>
                                <!-- END INFO BLOCK -->

                                <!-- BEGIN CAROUSEL -->
                                <div class="col-md-6 front-carousel">
                                    <img class="img img-responsive" src="/public/bdsltp/public/images/banner/nha1.jpg" alt=""/>
                                </div>
                                <!-- END CAROUSEL -->
                                <div class="clearfix" ></div>
                                <div class="text-center padding-top-20" >
                                    <h2>Công Ty Lê Thuật Phát Chuyên Thiết Kế Biệt Thự, Xây Dựng Trọn Gói</h2>
                                    <p>Cùng Kiến An chiêm ngưỡng 500+ mẫu thiết kế biệt thự cổ điển, biệt thự tân cổ điển, biệt thự hiện đại, biệt thự vườn, biệt thự phố, biệt thự mini...</p>
                                </div>


                            </div>



                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="main">

            <!-- BEGIN SIDEBAR & CONTENT -->
            <div class="margin-bottom-40">
                <!-- BEGIN CONTENT -->
                <div class="col-md-12 col-sm-12">
                    <h1 class="text-center title-pannel" ><span>MẪU BIỆT THỰ ĐẸP</span></h1>
                    <div class="content-page">
                        <div class="filter-v1">
                            <ul class="mix-filter hidden">
                                <li data-filter="all" class="filter active">All</li>
                                <li data-filter="category_1" class="filter">UI Design</li>
                                <li data-filter="category_2" class="filter">Web Development</li>
                                <li data-filter="category_3" class="filter">Photography</li>
                                <li data-filter="category_3 category_1" class="filter">Wordpress and Logo</li>
                            </ul>
                            <div class="row mix-grid thumbnails">
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha1.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha1.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_2 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha2.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto accusamus</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha2.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha3.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha3.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha1.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha1.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_2 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha2.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto accusamus</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha2.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha3.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha3.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha1.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha1.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_2 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha2.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto accusamus</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha2.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha3.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha3.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha1.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha1.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_2 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha2.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto accusamus</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha2.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-4 mix category_1 mix_all" style="display: block; opacity: 1; ">
                                    <div class="mix-inner">
                                        <img alt="" src="/public/bdsltp/public/images/banner/nha3.jpg" class="img-responsive">
                                        <div class="mix-details">
                                            <h4>Cascusamus et iusto odio</h4>
                                            <a class="mix-link"><i class="fa fa-link"></i></a>
                                            <a data-rel="fancybox-button" title="Project Name" href="/public/images/banner/nha3.jpg" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
                <!-- END CONTENT -->
            </div>
            <!-- BEGIN SIDEBAR & CONTENT -->
            <!-- BEGIN RECENT WORKS -->
            <div class="recent-work margin-bottom-40">
                <div class="col-md-12">
                    <hr>
                    <h1 class="text-center title-pannel" ><span>Thông Tin Cần Biết</span></h1>
                    <div class="owl-carousel owl-carousel4">
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <h3>Cam kết dịch vụ tại Kiến An</h3>
                                </a>
                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <h3>Bảng giá thiết kế kiến trúc Kiến An</h3>


                                </a>

                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <h3>Quy trình xây dựng tại Kiến An</h3>


                                </a>

                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <h3>Quy trình thiết kế tại Kiến An</h3>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- END RECENT WORKS -->

            <!-- BEGIN RECENT WORKS -->
            <div class="recent-work margin-bottom-40">
                <div class="col-md-12">
                    <hr>
                    <h1 class="text-center title-pannel" ><span>Xây Dựng Trọn Gói</span></h1>
                    <div class="owl-carousel owl-carousel4">
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <strong>Amazing Project</strong>
                                    <b>Agenda corp.</b>
                                </a>
                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <strong>Amazing Project</strong>
                                    <b>Agenda corp.</b>
                                </a>
                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <strong>Amazing Project</strong>
                                    <b>Agenda corp.</b>
                                </a>
                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <strong>Amazing Project</strong>
                                    <b>Agenda corp.</b>
                                </a>
                            </div>
                        </div>
                        <div class="recent-work-item">
                            <div class="item-content" >
                                <em>
                                    <img src="/public/bdsltp/public/images/banner/nha1.jpg" alt="Amazing Project" class="img-responsive">
                                    <a href="portfolio-item.html"><i class="fa fa-link"></i></a>
                                    <a href="/public/images/banner/nha1.jpg" class="fancybox-button" title="Project Name #1" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                                </em>
                                <a class="recent-work-description" href="javascript:;">
                                    <strong>Amazing Project</strong>
                                    <b>Agenda corp.</b>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END RECENT WORKS -->
            <!-- BEGIN RECENT WORKS -->
            <div class="margin-bottom-40">
                <div class="col-md-12">
                    <hr>
                    <h1 class="text-center title-pannel" ><span>KHÁCH HÀNG NÓI VỀ Chúng Tôi</span></h1>
                    <div id="myCarousel1" class="padding-top-40">
                        <!-- Carousel items -->
                        <div class="carousel-inner khachangnoigi owl-carousel3">
                            <div class="item">
                                <div class="khachangnoigi-content" >
                                    <div class="col-md-4">
                                        <img class="img img-responsive img-circle" style="border-radius: 100px;" src="/public/bdsltp/public/theme/assets/pages/img/people/img1-small.jpg" alt="">
                                        <div class="">
                                            <span class="testimonials-name">Nguyễn Văn A</span>
                                            <span class="testimonials-post">Giám Đốc</span>
                                        </div>
                                    </div>
                                    <blockquote class="col-md-8" ><p>Thiết kế kiến trúc sáng tạo, vượt yêu cầu mà tôi đưa ra. Cảm ơn công ty đã cho tôi và gia đình có được ngôi nhà như tôi mong muốn.</p></blockquote>
                                    <div class="clearfix" ></div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="khachangnoigi-content" >
                                    <div class="col-md-4">
                                        <img class="img img-responsive img-circle" style="border-radius: 100px;" src="/public/bdsltp/public/theme/assets/pages/img/people/img1-small.jpg" alt="">
                                        <div class="">
                                            <span class="testimonials-name">Nguyễn Văn A</span>
                                            <span class="testimonials-post">Giám Đốc</span>
                                        </div>
                                    </div>
                                    <blockquote class="col-md-8" ><p>
                                            Rất cảm thấy rất an tâm khi giao công trình cho Kiến An Corp và tôi đã đúng khi công trình diễn ra rất suôn sẻ, nhanh chóng, bàn giao tốt đẹp.</p></blockquote>
                                    <div class="clearfix" ></div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="khachangnoigi-content" >
                                    <div class="col-md-4">
                                        <img class="img img-responsive img-circle" style="border-radius: 100px;" src="/public/bdsltp/public/theme/assets/pages/img/people/img1-small.jpg" alt="">
                                        <div class="">
                                            <span class="testimonials-name">Nguyễn Văn A</span>
                                            <span class="testimonials-post">Giám Đốc</span>
                                        </div>
                                    </div>
                                    <blockquote class="col-md-8" ><p>
                                            Tôi thích gì đơn giản thôi nên cũng bảo kiến trúc sư vậy. Đơn giản mà đừng đơn điệu quá nhìn vào nhà chẳng thấy gì hay hết trơn thì không được. Kiến An thiết kế là tôi thấy được liền là triển khai luôn thôi!</p></blockquote>
                                    <div class="clearfix" ></div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="khachangnoigi-content" >
                                    <div class="col-md-4">
                                        <img class="img img-responsive img-circle" style="border-radius: 100px;" src="/public/bdsltp/public/theme/assets/pages/img/people/img1-small.jpg" alt="">
                                        <div class="">
                                            <span class="testimonials-name">Nguyễn Văn A</span>
                                            <span class="testimonials-post">Giám Đốc</span>
                                        </div>
                                    </div>
                                    <blockquote class="col-md-8" ><p> Thông thường mọi người xây nhà là qua người quen giới thiệu cho yên tâm. Nhưng tôi thì tôi thích tự mình tìm tự mình quyết. Kiến An xây cho tôi căn nhà tôi đặc biệt ưng ý. Nhiều lúc cũng vui vì mọi người khen hay tạo dáng chụp hình trước cổng nhà mình lắm.</p></blockquote>
                                    <div class="clearfix" ></div>
                                </div>
                            </div>


                        </div>
                        <!-- Carousel nav -->
                        <a class="left-btn" href="#myCarousel1" data-slide="prev"></a>
                        <a class="right-btn" href="#myCarousel1" data-slide="next"></a>
                    </div>
                </div>
            </div>
            <div class="clearfix" ></div>
            <div class="tuvan-container margin-10" >
                <p class="text-center" >NHANH LÊN! HÃY GỌI NGAY CHÚNG TÔI</p>
                <h3 class="text-center" >ĐỂ ĐƯỢC TƯ VẤN MIỄN PHÍ</h3>
                <div class="btn-tuvan text-center" >
                    <a href="" class="btn-lg btn-bds btn btn-primary btn-radius" >Đăng Ký Tư Vấn Miễn Phí</a>
                    <a href="" class="btn-lg btn-bds btn btn-primary btn-radius" >Hotline: 1234.123.123</a>
                    <a href="" class="btn-lg btn-bds btn btn-primary btn-radius" >Đặt Lịch Hẹn Với Kiến Trúc Sư</a>

                </div>
            </div>
            <!-- END RECENT WORKS -->


        </div>

        <!-- BEGIN PRE-FOOTER -->
        <div class="pre-footer">
            <div class="container">
                <div class="row">
                    <!-- BEGIN BOTTOM ABOUT BLOCK -->
                    <div class="col-md-4 col-sm-6 pre-footer-col">
                        <div class="text-center">
                            <img style="height: 200px;margin: auto;" src="/public/bdsltp/public/images/logo.svg" alt="__webName___">
                        </div>
                        <p class="text-justify" >Công ty tư vấn thiết kế biệt thự Lê Thuận Phát được thành lập với mong muốn trở thành địa chỉ tin cậy, chuyên sâu về lĩnh vực thiết kế và xây dựng nhà ở, biệt thự cùng những hạng mục thi công hoàn thiện, nội thất khác trong công trình. Chúng tôi là những chuyên gia tiên phong trong các giải pháp thiết kế xây dựng nhà ở dân dụng tại Việt Nam.</p>

                    </div>
                    <!-- END BOTTOM ABOUT BLOCK -->

                    <!-- BEGIN BOTTOM CONTACTS -->
                    <div class="col-md-4 col-sm-6 pre-footer-col">
                        <h2>Liên Hệ</h2>
                        <address class="margin-bottom-40">
                            <p>Địa Chỉ: 35, Lorem Lis Street, Park Ave
                                California, US</p>
                            <p>Phone: 300 323 3456</p>
                            <p>Fax: 300 323 1456</p>
                            <p>Email: <a href="mailto:info@metronic.com">info@metronic.com</a></p>
                            <p>Skype: <a href="skype:abc">vandovodoi</a></p>
                        </address>


                    </div>
                    <!-- END BOTTOM CONTACTS -->

                    <!-- BEGIN TWITTER BLOCK -->
                    <div class="col-md-4 col-sm-6 pre-footer-col">

                        <h2>Nhận Tin</h2>
                        <p>Đăng ký nhận bản tin của chúng tôi và cập nhật những tin tức và ưu đãi mới nhất!</p>
                        <div class="pre-footer-subscribe-box pre-footer-subscribe-box-vertical">
                            <form action="#">
                                <div class="input-group">
                                    <input type="text" placeholder="youremail@mail.com" class="form-control">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">Gửi</button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- END TWITTER BLOCK -->
                </div>
            </div>
        </div>
        <!-- END PRE-FOOTER -->

        <!-- BEGIN FOOTER -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- BEGIN COPYRIGHT -->
                    <div class="col-md-4 col-sm-4 padding-top-10">
                        2015 © . ALL Rights Reserved.
                    </div>
                    <!-- END COPYRIGHT -->
                    <!-- BEGIN PAYMENTS -->
                    <div class="col-md-4 col-sm-4">
                        <ul class="social-footer list-unstyled list-inline pull-right">
                            <li><a href="javascript:;"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-skype"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-github"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-youtube"></i></a></li>
                            <li><a href="javascript:;"><i class="fa fa-dropbox"></i></a></li>
                        </ul>
                    </div>
                    <!-- END PAYMENTS -->
                    <!-- BEGIN POWERED -->
                    <div class="col-md-4 col-sm-4 text-right">
                        <p class="powered">titkul</p>
                    </div>
                    <!-- END POWERED -->
                </div>
            </div>
        </div>

        <?php
        functionLayout::js();
        ?>

    </body>
</html>
<?php
functionLayout::DecodeHTML();
?>